### ISSUE TITLE
Cannot always see any value in a raw difference map

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#191] opened 2015-11-09 22:37 UTC
The raw difference map (below) does not include any values for the user. The legend shows only a value of 0 with colors above and below that point. All colors in the map are correctly above 0, but there is no way for the user to determine any value. The probe tool is not available for a raw difference map and the legend basically says that all values are non-negative.

![c-port_rawdiff_formxe7_novalues](https://cloud.githubusercontent.com/assets/10145737/11048833/190c003c-8708-11e5-8156-3280a4ff9ec1.PNG)
(Savannah, GA; annual concentrations; formaldehyde; Ships-in-transit as only emissions source category; raw difference between base emissions and emissions with a constant multiplier)

**Comment by cseppan** [comment] 2015-11-09 22:57
Duplicate of issue #165.

**Closed by cseppan** 2015-11-09 22:57 UTC
