### ISSUE TITLE
C-LINE annual averages - odd behavior

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#153] opened 2015-07-06 21:07 UTC
C-LINE does not produce any concentrations when run for Diesel PM25 annual averages in Charleston SC. I downloaded the outputs are the concentrations are all zero.

The annual averages for 1,3-Butadiene do not display, but there are non-zero concentrations in the outputs.

The hourly averages for both these pollutants work just fine, it's just the annual.

**Comment by michellegrace** [comment] 2015-07-15 13:36
Catherine tracked this down to an indexing error in the aa_road_compute_hourlyemissions.f90 routine. This is now fixed, in addition to some other minor updates. 

I am leaving this ticket open and assigning it to Catherine. She wanted to check the 2nd sentence to make sure it was not an interpolation error in her code. I will let her close this issue.

**Comment by cseppan** [comment] 2015-07-20 04:34
Confirmed that values in Kevin's run from July 6th were less than the 10^-6 threshold due to missing grams to micrograms conversion. Did a fresh run with the latest CTOOLS_ANNUAL executable. Values now correctly reported in micrograms, so overlay plot displays as expected.

**Closed by cseppan** 2015-07-20 04:34 UTC
Labels: bug
